### ISSUE TITLE
Opening new instance every time on share 

### ISSUE THREAD

**Issue by SafdarSikander** [ajith-ab/react-native-file-share-intent#1]
Share the image / Text will start a new instance even the App is already running. I have a tired android:launceMode="SingleTask" but in that case, Share is only working if the App is closed not working if App is in background.

**Comment by ajith-ab** [comment]
include the android:launchMode="singleTask" and it will not be possible to have multiple instances of your Activity launched at the same time.


change your manifest like this:

 

```
   <activity
        android:name="com.yourpackage.YourActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>

```

**Comment by ankitsehgal94** [comment]
@ajith-ab  Facing the same issue of not able to get file path in backgroundState even after adding
1. andriod:documentLaunchMode = 'never'
2. android:launchMode= 'singleTask'
3. appState to check if its in background

In the example given, it will get called only once in componentDidMount . 
Can you share an example to get filePath when app is in background than in killed state.

**Comment by ajith-ab** [comment]
@ankitsehgal94 As an Experiment   Remove the `android:launchMode= 'singleTask'`  and use `android:allowTaskReparenting="true"`. Now I am trying to build with  event listener when Receiving intents

**Comment by kartikpr** [comment]
Same issue 
Any updates @ajith-ab

**Comment by azharuddinkhan8898** [comment]
> @ajith-ab Facing the same issue of not able to get file path in backgroundState even after adding
> 
> 1. andriod:documentLaunchMode = 'never'
> 2. android:launchMode= 'singleTask'
> 3. appState to check if its in background
> 
> In the example given, it will get called only once in componentDidMount .
> Can you share an example to get filePath when app is in background than in killed state.

Remove `android:launchMode= 'singleTask'` and add `andriod:documentLaunchMode = 'never'`. This is working fine.
