### ISSUE TITLE
iOS not working with react native 0.61.1

### ISSUE THREAD

**Issue by sidpauhal** [ajith-ab/react-native-file-share-intent#10]
Hi Can you update the documentation for manual installation in iOS
I followed the steps mentioned in the docs but was not able to build for ios
Android is working but IOS is not.
Previously tried react native version 0.60.5 but failed.

package.json file
"dependencies": {
    "@react-native-firebase/app": "^6.0.0",
    "@react-native-firebase/ml-vision": "^6.0.0",
    "react": "16.9.0",
    "react-native": "0.61.1",
    "react-native-file-share-intent": "^1.1.2",
    "rn-fetch-blob": "^0.11.2"
  },

**Comment by jeffelector** [comment]
same problem here .
please provide answer, you dont supply us support!

**Comment by eladni101** [comment]
+1

**Comment by pulselife** [comment]
Android, react native 0.61.5 it is not working too.

**Comment by DaveLomber** [comment]
We ran Android 0.61, with some issues, but mainly it works

but re iOS 0.61 - seems the project is not compatible with it, and the guide is outdated

**Comment by Jerome91410** [comment]
Didn't check right now on Android.
But it's possible to make it works on ios with rn 0.61.5

You have to link with your pod instead of React lib and patch this package:
```
diff --git a/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj b/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj
index a3bdf9c..26f653b 100644
--- a/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj
+++ b/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj
@@ -215,8 +215,7 @@
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
-					"$(SRCROOT)/../../../React/**",
-					"$(SRCROOT)/../../react-native/React/**",
+					"$(SRCROOT)/../../../ios/Pods/Headers/Public/**",
 				);
 				LIBRARY_SEARCH_PATHS = "$(inherited)";
 				OTHER_LDFLAGS = "-ObjC";
@@ -231,8 +230,7 @@
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
 					/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
-					"$(SRCROOT)/../../../React/**",
-					"$(SRCROOT)/../../react-native/React/**",
+					"$(SRCROOT)/../../../ios/Pods/Headers/Public/**",
 				);
 				LIBRARY_SEARCH_PATHS = "$(inherited)";
 				OTHER_LDFLAGS = "-ObjC";
```

**Comment by narenderChatha** [comment]
@Jerome91410  i am facing same issue. will you please explore step by step?
i want to know how can i do this. "You have to link with your pod instead of React lib and patch the package:" and what do mean by this
"diff --git a/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj b/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj
index a3bdf9c..26f653b 100644
--- a/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj
+++ b/node_modules/react-native-file-share-intent/ios/RNFileShareIntent.xcodeproj/project.pbxproj
@@ -215,8 +215,7 @@"

**Comment by Jerome91410** [comment]
@narenderChatha into your podfile, you have to create a target "share" which contains this package + react native required packages

So you have to follow the ios instructions
https://github.com/ajith-ab/react-native-file-share-intent/tree/master/ios

And add the patch provided before : 
- install https://github.com/ds300/patch-package
- create a "patches" directory in the root folder
- put the content provided before into a filename 'react-native-intent-launcher+0.2.1.patch'

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by narenderChatha** [comment]
thank u so much
