### ISSUE TITLE
Getting error with URL share (brave browser)

### ISSUE THREAD

**Issue by annraveendran** [ajith-ab/react-native-file-share-intent#14]
Share is working in safari but getting error in brave.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'*** First throw call stack:

Could you please check.

**Comment by ajith-ab** [comment]
Duplicate of #10

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
