### ISSUE TITLE
(Android) intent.getAction() returns null when opening from external app

### ISSUE THREAD

**Issue by sslash** [ajith-ab/react-native-file-share-intent#16]
I'm trying to open an OPML (xml) file with the RN app I've built. I get my app as an option when pressing "open with" in the external app, but when my app opens, nothing happens. I've debugged this and both `intent.getAction()` and `intent.getType();` returns null. Here's my manifest:
```
<intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="application/xml"/>
                <data android:mimeType="text/xml"/>
                <data android:mimeType="text/x-opml"/>
            </intent-filter>
```

Any idea of what's happening?

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by davidsalib** [comment]
Having this issue on the new package @ajith-ab  referenced. Any ideas what could be causing this?
