### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by 1appstudio** [ajith-ab/react-native-file-share-intent#19]
I have successfully implemented 'react-native-file-share-intent' through npm install on my root directory and follow everything what you mentioned in
https://github.com/ajith-ab/react-native-file-share-intent/tree/master/ios for IOS. But unfortunately, its not working in iOS mobile (iPad-mini, iPhone 6+), I am getting following error.

Unhandled JS Exception: TypeError: _reactNativeFileShareIntent.default.getFilepath is not a function. (In '_reactNativeFileShareIntent.default.getFilepath(function (url) {
_this3.setState({
fileUrl: url
});
})', '_reactNativeFileShareIntent.default.getFilepath' is undefined)

This error is located at:
in App (at renderApplication.js:35)
in RCTView (at View.js:45)
in View (at AppContainer.js:98)
in RCTView (at View.js:45)
in View (at react-native-root-siblings/index.js:34)
in RootSiblingsWrapper (at AppContainer.js:112)
in RCTView (at View.js:45)
in View (at AppContainer.js:115)
in AppContainer (at renderApplication.js:34)

Can you fix this issue?

**Comment by 1appstudio** [comment]
Can you please resolve the above issue

**Comment by claudepark** [comment]
you should change getFilepath to getFilePath.

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
