### ISSUE TITLE
getFilepath vs. getFilePath

### ISSUE THREAD

**Issue by RAMart** [ajith-ab/react-native-file-share-intent#2]
Thanks for your react-native module!

I noticed that the android implementation exposes a function called `getFilepath` whereas the ios implementation uses `getFilePath`.
I propose to use the same name for both implementations to make sharing code even more simpler.

**Comment by ajith-ab** [comment]
@RAMart I will Fix in Next Updates.

**Comment by RAMart** [comment]
Then you shouldn't close this issue until then?
