### ISSUE TITLE
Not working on Youtube app

### ISSUE THREAD

**Issue by claudepark** [ajith-ab/react-native-file-share-intent#22]
It is working on the Safari app. 
but not working on the Youtube app.
It is not responding to the click share button on the Youtube app.
Is it possible?

**Comment by claudepark** [comment]
I fount out this issue.

orgin source
```
[ShareFileIntentModule_itemProvider loadItemForTypeIdentifier:(NSString *)kUTTypeText options:nil completionHandler:^(**NSUrl** *url, NSError *error) {
           callback(@[**url.absoluteString**]);
}];
```
I changed this
```
[ShareFileIntentModule_itemProvider loadItemForTypeIdentifier:(NSString *)kUTTypeText options:nil completionHandler:^(**NSString** *url, NSError *error) {
           callback(@[**url**]);
}];
```

**Comment by LeonardoPlacanica** [comment]
Hi,
I had the exact same issue with Youtube and this solved it for me. I still have errors on Flipboard and NYT apps even Whatspp. Do you possbily know a work around for those app either?
Thanks @claudepark

**Comment by pdooo** [comment]
I have same issue. Any solutions?

**Comment by LeonardoPlacanica** [comment]
Yeah actually I forked this to work in every app. You can find the solution in the fork on my profile!

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
