### ISSUE TITLE
How to know the url data type.

### ISSUE THREAD

**Issue by fabio-C** [ajith-ab/react-native-file-share-intent#25]
When I call this function:

```
RNFileShareIntent.getFilepath((url) => {
//url
});
```

URL can be anything: an image URI, a text, a http link, etc.
Is there a way to know what kind of data I am receiving? For example a "type" params.

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
