### ISSUE TITLE
Url not updated using documentLaunchMode=never

### ISSUE THREAD

**Issue by fabio-C** [ajith-ab/react-native-file-share-intent#27]
I can't solve this issue.

Here are the steps to reproduce it:

0. Setup **android:documentLaunchMode="never"** in your Android manifest.
1. Close all the apps.
2. Go to gallery, share an image, and the app will open with the url of the image. ok.
3. Leave the app in background and share another image from the gallery.
4. The app will open again but with the same url as before.

I notice that in step 4 the react method [getFilepath](https://github.com/ajith-ab/react-native-file-share-intent/blob/e3a96db7d2f1d720a204de5d21488d48d29a4fc7/android/src/main/java/com/ajithab/RNFileShareIntentModule.java#L39), is not fired.

N.B: This happens only if the app is closed the first time the image is shared. If we execute the steps with the app already opened, [getFilepath](https://github.com/ajith-ab/react-native-file-share-intent/blob/e3a96db7d2f1d720a204de5d21488d48d29a4fc7/android/src/main/java/com/ajithab/RNFileShareIntentModule.java#L39) is fired, and url is updated correctly.

The same issue happens without this library, with the code provided yby this tutorial: https://medium.com/swlh/sharing-image-to-android-app-using-intent-filter-to-react-native-d112308328d5, so maybe is something related to React Native in general.

Any idea?

-------------------------------------------------
Android 9
React native 0.62.2

**Comment by fabio-C** [comment]
Related with this issue of another library:
https://github.com/meedan/react-native-share-menu/issues/39

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
