### ISSUE TITLE
Example not working in iOS release configuration

### ISSUE THREAD

**Issue by RAMart** [ajith-ab/react-native-file-share-intent#3]
The example you kindly provided does not work for iOS in a release configuration.
Probably because of
> jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"Share" fallbackResource:nil];

in `Share Intent/ShareViewController.m`

Unfortunately, the usual

>#if DEBUG
>  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"Share" fallbackResource:nil];
>#else
>  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
>#endif

won't work here as well.
Any ideas of how to make the Example run in a release configuration?

**Comment by ajith-ab** [comment]
@RAMart 

- run command in the root folder

`react-native bundle --entry-file share.js --platform ios --dev false --bundle-output ios/share.jsbundle --assets-dest ios`

then open Xcode and  from side menu select the folder of  `share extension` and right-click the folder you will get a menu to `add files` then you will select the  `share.jsbundle`  from your ios folder 

update `ShareViewController.m`

`#if DEBUG
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"Share" fallbackResource:nil];
#else
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"share" withExtension:@"jsbundle"];
#endif`

**Comment by ForU** [comment]
@ajith-ab @RAMart, debug mode works fine, but release mode still not working in my project even tried the Ajith-ab's solution, I just wonder whether if the `share.jsbundle` has not been properly loaded by extension app (release mode) or something. So any help or hint, do I miss something?

And, as you can see `share.jsbundle` file has been successfully packed into .appex in attach files.

![](https://xgeneric.oss-cn-beijing.aliyuncs.com/tmp/GitHub/x.png)
![](https://xgeneric.oss-cn-beijing.aliyuncs.com/tmp/GitHub/y.png)

And, `ShareViewController.m` file:
```objective-c
#if DEBUG
  jsCodeLocation = [NSURL URLWithString:@"http://192.168.10.103:8081/Share.bundle?platform=ios&dev=true"];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"share" withExtension:@"jsbundle"];
#endif
```

thx.

**Comment by RAMart** [comment]
@ForU Did you try a release build of the provided example?

**Comment by ForU** [comment]
@RAMart en, I will give it a try, does it work on your side?

**Comment by RAMart** [comment]
@ForU Yes!

**Comment by ForU** [comment]
My bad, I mistakenly built `jsbundle` from a wrong `Share.js` file. Everything works fine, thanks @RAMart and thanks @ajith-ab for sharing such a nice project !
