### ISSUE TITLE
Filename and extension needed

### ISSUE THREAD

**Issue by Abandonedengineer** [ajith-ab/react-native-file-share-intent#5]
I'm able to use the package and it works perfectly fine but the thing is i need filename and extension of the file i shared could you tell me how ? i don't see anything of that sort in the docs

**Comment by ajith-ab** [comment]
next Update I will add this feature also

**Comment by ajith-ab** [comment]
Use [react-native-get-real-path](https://github.com/Wraptime/react-native-get-real-path)

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
