### ISSUE TITLE
Getting this error which leads to app to crash

### ISSUE THREAD

**Issue by kumbhar-ketan** [ajith-ab/react-native-file-share-intent#7]
Configure project :react-native-file-share-intent
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
