### ISSUE TITLE
How to share multiple files?

### ISSUE THREAD

**Issue by sidpauhal** [ajith-ab/react-native-file-share-intent#9]
Hi is there any way or example of sharing multiple files with this library.

My package.json file

"dependencies": {
    "@react-native-firebase/app": "^6.0.0",
    "@react-native-firebase/ml-vision": "^6.0.0",
    "react": "16.9.0",
    "react-native": "0.61.1",
    "react-native-file-share-intent": "^1.1.2",
    "rn-fetch-blob": "^0.11.2"
  },

**Comment by annraveendran** [comment]
Any update on this?

**Comment by nschild** [comment]
I'm interested too

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
